version: '3'

services:

  www-app-live:
    container_name: www-app-live
    image: quay.io/cressie176/www-app:live
    command: ['node', '.']
    restart: always
    depends_on:
      - www-nginx
      - www-mongo
    environment:
      - APP_ENV=live
    volumes:
      - ${CONTAINERS_DIR}/app-live/secrets:/opt/app/secrets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/__/status"]
      interval: $HEALTHCHECK_INTERVAL
      timeout: $HEALTHCHECK_TIMEOUT
      retries: 3

  www-app-stage:
    container_name: www-app-stage
    image: quay.io/cressie176/www-app:latest
    command: ['node', '.']
    restart: always
    depends_on:
      - www-nginx
      - www-mongo
    environment:
      - APP_ENV=stage
    volumes:
      - ${CONTAINERS_DIR}/app-stage/secrets:/opt/app/secrets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/__/status"]
      interval: $HEALTHCHECK_INTERVAL
      timeout: $HEALTHCHECK_TIMEOUT
      retries: 3

  www-app-local:
    container_name: www-app-local
    image: quay.io/cressie176/www-app:latest
    command: ['node', '.']
    restart: always
    depends_on:
      - www-nginx
      - www-mongo
    environment:
      - APP_ENV=local
    volumes:
      - ${CONTAINERS_DIR}/www-app-local/secrets:/opt/app/secrets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/__/status"]
      interval: $HEALTHCHECK_INTERVAL
      timeout: $HEALTHCHECK_TIMEOUT
      retries: 3

  www-nginx:
    container_name: www-nginx
    image: quay.io/cressie176/www-nginx
    restart: always
    volumes:
      - ${CONTAINERS_DIR}/nginx/etc/nginx/ssl:/etc/nginx/ssl
      - ${CONTAINERS_DIR}/jobs/var/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge
    ports:
      - 80:80
      - 443:443

  www-mongo:
    container_name: www-mongo
    image: mongo
    restart: always
    volumes:
      - ${CONTAINERS_DIR}/mongo/data/db:/data/db

  www-jobs:
    container_name: www-jobs
    image: quay.io/cressie176/www-jobs
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERS_DIR}/jobs/etc/letsencrypt:/etc/letsencrypt
      - ${CONTAINERS_DIR}/jobs/var/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge
      - ${CONTAINERS_DIR}/nginx/etc/nginx/ssl:/etc/nginx/ssl

 watchtower:
   container_name: watchtower
   restart: always
   image: v2tec/watchtower
   environment:
     - REPO_USER=${REPO_USER}
     - REPO_PASS=${REPO_PASS}
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   command: --interval 60 www-app-stage

networks:
  default:
    external:
      name: www
